core/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path('',include('property.urls')),
]
if settings.DEBUG:
    urlpatterns += static(
 settings.MEDIA_URL,
 document_root=settings.MEDIA_ROOT
 )

property/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', home_view, name='home'),
    path('signup/', signup_view, name='signup'),
    path('profile_setup/', agent_profile_setup_view, name='profile_setup'),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('dashboard/', dashboard, name='dashboard'),
    path('buy/', buy_properties, name='buy_properties'),
    path('sell/', sell_properties, name='sell_properties'),
    path('rent/', rent_properties, name='rent_properties'),
    path('commercial/', commercial_properties, name='commercial_properties'),
    path('agents/', agent_list, name='agent_list'),
    path('communities/', community_list, name='community_list'),
    path('community/<int:pk>/', community_detail_view, name='community_detail'),
    path('community/create/', community_create_view, name='community_create'),
    path('community/update/<int:pk>/', community_update_view, name='community_update'),
    path('community_delete/<int:pk>/', community_delete_view, name='community_delete'),
    path('property/create/', property_create_view, name='property_create'),
    path('property/update/<int:pk>/', property_update_view, name='property_update'),
    path('property/list/', property_list_view, name='property_list'),  # Add this line
    path('property/<slug:community>/<slug:property_name>', property_detail_view, name='property_detail'),
    path('property_delete/<int:pk>/', property_delete_view, name='property_delete'),
    path('searchbar/', searchbar, name='searchbar'),
    path('search/', search_properties, name='search'),
    path('inbox/', inbox, name='inbox'),
]

property/models.py
from django.contrib.auth.models import AbstractUser, Group, Permission
from django.db import models
from django.conf import *
from multiselectfield import MultiSelectField

class User(AbstractUser):
    ROLES = [
        ('buyer', 'Buyer'),
        ('agent', 'Agent'),
    ]
    role = models.CharField(max_length=10, choices=ROLES, default='buyer')
    contact_number = models.CharField(max_length=15, blank=True, null=True)
    is_agent = models.BooleanField(default=False)  # Determines if the user is an agent

    # Add unique related_name attributes to avoid clashes
    groups = models.ManyToManyField(
        Group,
        related_name="custom_user_set",  # Unique related_name
        blank=True,
        help_text="The groups this user belongs to.",
    )
    user_permissions = models.ManyToManyField(  
        Permission,
        related_name="custom_user_permissions_set",  # Unique related_name
        blank=True,
        help_text="Specific permissions for this user.",
    )

class Agent(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name="agent_profile")
    full_name = models.CharField(max_length=100)
    country = models.CharField(max_length=100)
    phone = models.CharField(max_length=15)
    whatsapp_number = models.CharField(max_length=15, blank=True, null=True)
    profile_picture = models.ImageField(upload_to="agents/profile_pictures", blank=True, null=True)
    about = models.TextField(blank=True, null=True)
    email = models.EmailField(unique=True)
    languages = models.CharField(max_length=200, help_text="Comma-separated list of languages.")
    properties_listed = models.IntegerField(default=0)
    communities_active_in = models.IntegerField(default=0)

    def __str__(self):
        return self.full_name

class Community(models.Model):
    name = models.CharField(max_length=100)
    location = models.CharField(max_length=100)
    images = models.ImageField(upload_to="communities/images")
    agent = models.ForeignKey(Agent, related_name="communities", on_delete=models.SET_NULL, null=True, blank=True)
    description = models.TextField(null=True, blank=True,default="No description")
    slug= models.SlugField(max_length=100,unique=True)
    def properties_count(self):
        return self.properties.count()

    def __str__(self):
        return self.name

class Property(models.Model):
    PROPERTY_TYPE_CHOICES = [
        ('residential', 'Residential'),
        ('commercial', 'Commercial'),
    ]

    FACILITY_CHOICES = [
        ('villa', 'Villa'),
        ('compound', 'Compound'),
        ('apartment', 'Apartment'),
        ('hotel_apartment', 'Hotel Apartment'),
        ('duplex', 'Duplex'),
    ]

    FACILITIES = [
        ('central_ac', 'Central A/C'),
        ('maids_room', "Maids Room"),
        ('balcony', "Balcony"),
        ('shared_pool', "Shared Pool"),
        ('shared_spa', "Shared Spa"),
        ('shared_gym', "Shared Gym"),
        ('concierge_service', "Concierge Service"),
        ('covered_parking', "Covered Parking"),
        ('view_of_water', "View of Water"),
        ('view_of_landmark', "View of Landmark"),
        ('pets_allowed', "Pets Allowed"),
        ('study', "Study"),
        ('private_garden', "Private Garden"),
        ('private_pool', "Private Pool"),
        ('private_gym', "Private Gym"),
        ('private_jacuzzi', "Private Jacuzzi"),
        ('built_in_wardrobes', "Built in Wardrobes"),
        ('walk_in_closet', "Walk-in Closet"),
        ('built_in_kitchen_appliances', "Built in Kitchen Appliances"),
        ('maid_service', "Maid Service"),
        ('childrens_play_area', "Children's Play Area"),
        ('childrens_pool', "Children's Pool"),
        ('barbecue_area', "Barbecue Area"),
    ]

    title = models.CharField(max_length=200)
    description = models.TextField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    location = models.CharField(max_length=100)
    slug = models.SlugField(max_length=100,unique=True,blank=True)
    property_type = models.CharField(max_length=50, choices=PROPERTY_TYPE_CHOICES)
    facility_type = models.CharField(max_length=50, choices=FACILITY_CHOICES)
    size = models.DecimalField(max_digits=10, decimal_places=2, help_text="Size in square feet.")
    bedrooms = models.PositiveIntegerField()
    bathrooms = models.PositiveIntegerField()
    facilities = MultiSelectField(max_length=500,choices=FACILITIES, blank=True, null=True)
    community = models.ForeignKey(Community, related_name="properties", on_delete=models.SET_NULL, null=True, blank=True)
    agent = models.ForeignKey(Agent, related_name="properties", on_delete=models.SET_NULL, null=True, blank=True)
    is_for_sale = models.BooleanField(default=False)
    is_for_rent = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.title

class PropertyImage(models.Model):
    property = models.ForeignKey(Property, related_name='images', on_delete=models.CASCADE)
    image = models.FileField(upload_to="properties/images")

    def __str__(self):
        return f"Image for {self.property.title}"

property/views.py
# Create your views here.
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate,logout
from django.contrib.auth.forms import AuthenticationForm
from django.contrib import messages
from .forms import *
from .models import *
def logout_view(request):
    if request.user.is_authenticated:
        logout(request)  # Logs out the user
        request.session.flush()  # Clears all session data
    return redirect('home')  # Redirect to the homepage
from django.db import IntegrityError

# def signup_view(request):
#     if request.method == 'POST':
#         # Extract form data from the request
#         username = request.POST.get('username')
#         email = request.POST.get('email')
#         first_name = request.POST.get('first_name')
#         last_name = request.POST.get('last_name')
#         contact_number = request.POST.get('contact_number')
#         password1 = request.POST.get('password1')
#         password2 = request.POST.get('password2')
#         role = request.POST.get('role')

#         # Initialize an error dictionary
#         errors = {}

#         # Validate passwords
#         if password1 != password2:
#             errors['password'] = "Passwords do not match."

#         # Check if the username already exists
#         if User.objects.filter(username=username).exists():
#             errors['username'] = "This username is already taken."

#         # Additional email validation (optional)
#         if User.objects.filter(email=email).exists():
#             errors['email'] = "An account with this email already exists."

#         # If there are any errors, re-render the form with the errors
#         if errors:
#             return render(request, 'property/signup.html', {'errors': errors})

#         # Create the user
#         try:
#             user = User.objects.create_user(
#                 username=username,
#                 email=email,
#                 first_name=first_name,
#                 last_name=last_name,
#                 password=password1
#             )
#             # You can save additional user-related data here if needed
#             # For example, if you have a Profile model:
#             # Profile.objects.create(user=user, contact_number=contact_number, role=role)
#             user.save()

#             return redirect('login')  # Redirect to the login page or any other page
#         except IntegrityError:
#             errors['general'] = "An error occurred while creating your account. Please try again."
#             return render(request, 'property/signup.html', {'errors': errors})

#     # Render the signup page for GET requests
#     return render(request, 'property/signup.html')

def signup_view(request):
    if request.method == 'POST':
        form = UserSignupForm(request.POST)
        if form.is_valid():
            user = form.save()
            role = form.cleaned_data['role']
            login(request, user)
            print(role)
            if role == "agent":
                return redirect('profile_setup')
            else:
                return redirect('home')
        else:
            messages.error(request, "Error in form submission.")
    else:
        form = UserSignupForm()
    return render(request, 'property/signup.html', {'form': form})

def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            redirect_back = request.POST.get('redirect_back', None)
            if redirect_back:
                return redirect(str(redirect_back))
            else:
                return redirect('home')
        else:
            messages.error(request, "Invalid username or password.")
    else:
        form = AuthenticationForm()
    return render(request, 'property/login.html', {'form': form})

def agent_profile_setup_view(request):
    if not(request.user.is_authenticated):
        return redirect('home')

    if request.method == 'POST':
        form = AgentProfileForm(request.POST, request.FILES)
        if form.is_valid():
            agent = form.save(commit=False)
            agent.user = request.user
            agent.save()
            request.user.is_agent=True
            messages.success(request, "Agent profile setup completed.")
            return redirect('home')
    else:
        form = AgentProfileForm()
    return render(request, 'property/agentProfileSetup.html', {'form': form})

def buy_properties(request):
    properties = Property.objects.filter(is_for_sale=True)
    print(len(properties))
    paginator = Paginator(properties,5)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    try:
        page_obj = paginator.get_page(page_number)
    except (PageNotAnInteger, ValueError):
        # If page is not an integer, deliver the first page
        page_obj = paginator.page(1)
    except EmptyPage:
        # If page is out of range, deliver the last page
        page_obj = paginator.page(paginator.num_pages)
    for property in properties:
        images = property.images.all()
        for image in images:
            print(image.image)
    
    return render(request, template_name='property/buy.html', context={'dataSet': properties,'page_obj':page_obj})
def sell_properties(request):  
    return render(request, template_name='property/sell.html')
def rent_properties(request):
    properties = Property.objects.filter(is_for_rent=True)
    paginator = Paginator(properties,5) 
    page_number = request.GET.get('page', 1)
    page_obj = paginator.get_page(page_number)
    try:
        page_obj = paginator.get_page(page_number)
    except (PageNotAnInteger, ValueError):
        # If page is not an integer, deliver the first page
        page_obj = paginator.page(1)
    except EmptyPage:
        # If page is out of range, deliver the last page
        page_obj = paginator.page(paginator.num_pages)
    for property in properties:
        images = property.images.all()
        for image in images:
            print(image.image)                                                                                      
    return render(request, template_name='property/rent.html',context={'dataSet': properties,'page_obj':page_obj})


def community_create_view(request):
    if request.user.is_authenticated:
        if request.user.is_agent:
            if request.method == 'POST':
                form = CommunityForm(request.POST)
                if form.is_valid():
                    form.save()
                    return redirect('community_list')
            else:
                form = CommunityForm()
            return render(request, 'property/community_create.html', {'form': form})
        else:
            return redirect('home')
    else:
        return redirect('login')

def commercial_properties(request): 
    properties = Property.objects.filter(property_type="commercial")
    paginator = Paginator(properties,5)
    page_number = request.GET.get('page', 1)
    page_obj = paginator.get_page(page_number)
    try:
        page_obj = paginator.get_page(page_number)
    except (PageNotAnInteger, ValueError):
        # If page is not an integer, deliver the first page
        page_obj = paginator.page(1)
    except EmptyPage:
        # If page is out of range, deliver the last page
        page_obj = paginator.page(paginator.num_pages)
    for property in properties:
        images = property.images.all()
        for image in images:
            print(image.image)
    
    return render(request, template_name='property/commercial.html', context={'dataSet': properties,'page_obj':page_obj})
def agent_list(request):
    agents = Agent.objects.all()
    paginator = Paginator(agents, 5)  
    page_number = request.GET.get('page', 1)
    page_obj = paginator.get_page(page_number)
    try:
        page_obj = paginator.get_page(page_number)
    except (PageNotAnInteger, ValueError):
        # If page is not an integer, deliver the first page
        page_obj = paginator.page(1)
    except EmptyPage:
        # If page is out of range, deliver the last page
        page_obj = paginator.page(paginator.num_pages)                                                                                 
    return render(request, template_name='property/agents.html',context={'data':agents,'page_obj':page_obj})
def community_list(request):                                                                           
    communities = Community.objects.all()
    return render(request, template_name='property/communities.html',context={'data':communities})
def home_view(request):
    if request.user.is_authenticated:
        return render(request, template_name='property/home.html',context={'user':request.user})
    else:
        return render(request, template_name='property/home.html')

def property_create_view(request):
    if request.method == 'POST':
        # images = forms.FileField(widget=forms.ClearableFileInput(attrs={'multiple': True}), required=False)
        form = PropertyForm(request.POST, request.FILES)

        if form.is_valid():
            formWhichNoOneSaved = form.save()
            images = request.FILES.getlist('images')  # Get the list of images
            for image in images:
                new_image = PropertyImage(property=formWhichNoOneSaved, image=image)
                new_image.save()
            
                

            return redirect('buy_properties')  # Replace with your property list view name
    else:
        form = PropertyForm()
    return render(request, 'property/property_create.html', {'form': form})

def community_update_view(request, pk):
    if request.user.is_authenticated:
        if request.user.is_agent:
            community_instance = Community.objects.get(id=pk)
            if request.method == 'POST':

property/templates/property/agentProfileSetup.html
<!DOCTYPE html>
<html>
<head>
    {% load static %}
    <title>Agent Profile Setup</title>
    <link rel="stylesheet" href="{% static 'property/styles/signup.css' %}">

</head>
<body>
    <form method="post" enctype="multipart/form-data">
        <h2>Agent Profile Setup</h2>
        {% csrf_token %}
        {{ form }}
        <button type="submit">Save Profile</button>
    </form>
</body>
</html>

property/templates/property/community_create.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create Community</title>
    <link rel="stylesheet" href="{% static 'property/styles/property-create.css' %}">
</head>
<body>
    <form method="POST" enctype="multipart/form-data">
        <h1>Create Community</h1>
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Create Community</button>
    </form>
</body>
</html>

property/templates/property/dashboard.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Real Estate Agent Dashboard</title>
    <link rel="stylesheet" href="{% static 'property/styles/dashboard.css' %}">
</head>
<body>
    <header>
        {% if user.is_authenticated %}
            <h1>Real Estate Agent Dashboard</h1>
            <h4>Welcome {{user.first_name}}</h4>
        {% else %}
            <h1>Property Finder</h1>
            <h4>Find your dream home</h4>
        {% endif %}
    </header>
    <div class="container">
        <div class="main-content">
            <h2>Manage Your Properties</h2>
            <ul class="property-list">
                {% for property in properties %}
                    <li class="property-item">
                        <span>Property {{property.id}}: {{property.title}}</span>
                        <div>
                            <a href="{% url 'property_detail' property.id %}"><button>Details</button></a>
                            <a href="{% url 'property_update' property.id %}"><button>Update</button></a>
                            <a href="{% url 'property_delete' property.id %}"><button>Delete</button></a>
                            
                        </div>
                    </li>
                {% endfor %}
                
            </ul>
            <div class="actions">
                <a href="{% url 'property_create' %}"><button>Add New Property</button></a>
            </div>

            <h2>Manage Your Communities</h2>
            <ul class="property-list">
                {% for community in communities %}
                    <li class="property-item">
                        <span>Community {{community.id}}: {{community.title}}</span>
                        <div>
                            <a href="{% url 'community_detail' community.id %}"><button>Details</button></a>
                            <a href="{% url 'community_update' community.id %}"><button>Update</button></a>
                            <a href="{% url 'community_delete' community.id %}"><button>Delete</button></a>
                            
                        </div>
                    </li>
                {% endfor %}
            <div class="actions">
                <a href="{% url 'community_create' %}"><button>Add New Community</button></a>
            </div>
        </div>
    </div>

    <script>
        function updateProperty(propertyId) {
            alert(`Open update dialog for Property ID: ${propertyId}`);
            // Logic for opening property update dialog box
        }

        function deleteProperty(propertyId) {
            if (confirm('Are you sure you want to delete this property?')) {
                alert(`Property ID: ${propertyId} has been deleted.`);
                // Logic for deleting the property
            }
        }

        function goToCreateProperty() {
            alert('Navigating to the property creation page...');
            // Logic for navigating to property creation page
        }
    </script>
</body>
</html>

property/templates/property/login.html
<!DOCTYPE html>
<html>
<head>
    {% load static %}
    <title>Login</title>
    <link rel="stylesheet" href="{% static 'property/styles/login.css' %}">
</head>
<body>
    <form method="post">
        <h2>Login</h2>
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Login</button>
    </form>
</body>
</html>

property/templates/property/pagination.html
<div class="pagination-container">
    <!-- Previous Button -->
    <button class="pagination-btn" id="prev-btn"
            {% if page_obj.has_previous %}
                onclick="window.location.href='?page={{ page_obj.previous_page_number }}'"
            {% else %}
                disabled
            {% endif %}>
        ❮
    </button>

    <!-- Page Numbers -->
    <div class="pagination">
        {% for page_num in page_obj.paginator.page_range %}
            <a href="?page={{ page_num }}"
               class="page-number {% if page_num == page_obj.number %}active{% endif %}">
                {{ page_num }}
            </a>
        {% endfor %}
    </div>

    <!-- Next Button -->
    <button class="pagination-btn" id="next-btn"
            {% if page_obj.has_next %}
                onclick="window.location.href='?page={{ page_obj.next_page_number }}'"
            {% else %}
                disabled
            {% endif %}>
        ❯
    </button>
</div>

property/templates/property/property_create.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create Property</title>
    <link rel="stylesheet" href="{% static 'property/styles/property-create.css' %}">
</head>
<body>
    <form method="POST" enctype="multipart/form-data">
        <h1>Create Property</h1>
        {% csrf_token %}
        {{ form.as_p }}
        <label for="images">Property Images:</label>
        <input type="file" name="images" multiple>
        <button type="submit">Create Property</button>
    </form>
</body>
</html>

property/templates/property/property_detail.html
<html>
    <head>
        <title>Property Finder</title>
        <link rel="stylesheet" href="styles.css">
    </head>
    <body>
        <header>
            <h1>Property Finder</h1>
            <h4>Find your dream home</h4>
        </header>
        {% if property %}
            <div class="container">
                <div class="main-content">
                    <h2>Property Details</h2>
                    <div class="property-details">
                        <span>Property ID: {{property.id}}</span>
                        <span>Title: {{property.title}}</span>
                        <span>Location: {{property.location}}</span>
                        <span>Price: {{property.price}}</span>
                        <span>Area: {{property.area}}</span>
                        <span>Bedrooms: {{property.bedrooms}}</span>
                        <span>Bathrooms: {{property.bathrooms}}</span>
                        <span>Garage: {{property.garage}}</span>
                        <span>Swimming Pool: {{property.swimming_pool}}</span>
                        <span>Garden: {{property.garden}}</span>
                        <span>Property Type: {{property.property_type}}</span>
                        <span>Property Status: {{property.property_status}}</span>
                    </div>
                    <div class="actions">
                        <a href="{% url 'property_update' property.id %}"><button>Update</button></a>
                        <button onclick="deleteProperty('{{property.id}}')">Delete</button>
                    </div>
                </div>
            </div>
        {% else %}
            <div class="container">
                <div class="main-content">
                    <h2>Property Not Found</h2>
                    <p>The property you are looking for does not exist.</p>
                </div>
            </div>
        {% endif %}
    </body>
</html>

property/templates/property/signup.html
<!-- <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Signup</title>
</head>
<body style="font-family: Arial, sans-serif; background-color: #E7E5F4; margin: 0; padding: 0; display: flex; justify-content: center; align-items: center; height: 100vh;">
  <form method="POST" style="width: 100%; max-width: 750px; background: #FFFFFF; padding: 15px; border-radius: 8px; box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);">
    {% csrf_token %}  
    <h1 style="margin: 0 0 15px; text-align: center; color: #E63933;">Signup</h1>
      
      <div class="form-columns" style="display: flex; gap: 20px; justify-content: space-between;">
          <div class="column" style="flex: 1; display: flex; flex-direction: column; margin-right: 0;">
              <p style="margin-bottom: 10px;">
                  <label for="id_username" style="display: block; margin-bottom: 5px; font-weight: bold; color: #333;">Username:</label>
                  <input type="text" name="username" maxlength="150" autofocus required aria-describedby="id_username_helptext" id="id_username" style="width: 94%; padding: 8px; border: 1px solid #ddd; border-radius: 5px; font-size: 14px;">
                  <span class="helptext" id="id_username_helptext" style="font-size: 12px; color: #888; margin-top: 5px;">Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.</span>
                  <strong>{{ errors.username }}</strong>
              </p>
              <p style="margin-bottom: 10px;">
                  <label for="id_email" style="display: block; margin-bottom: 5px; font-weight: bold; color: #333;">Email address:</label>
                  <input type="email" name="email" maxlength="254" id="id_email" style="width: 94%; padding: 8px; border: 1px solid #ddd; border-radius: 5px; font-size: 14px;">
                  <strong>{{ errors.email }}</strong>
              </p>
              <p style="margin-bottom: 10px;">
                  <label for="id_first_name" style="display: block; margin-bottom: 5px; font-weight: bold; color: #333;">First name:</label>
                  <input type="text" name="first_name" maxlength="150" id="id_first_name" style="width: 94%; padding: 8px; border: 1px solid #ddd; border-radius: 5px; font-size: 14px;">
              </p>
              <p style="margin-bottom: 10px;">
                  <label for="id_last_name" style="display: block; margin-bottom: 5px; font-weight: bold; color: #333;">Last name:</label>
                  <input type="text" name="last_name" maxlength="150" id="id_last_name" style="width: 94%; padding: 8px; border: 1px solid #ddd; border-radius: 5px; font-size: 14px;">
              </p>
              <p style="margin-bottom: 10px;">
                  <label for="id_contact_number" style="display: block; margin-bottom: 5px; font-weight: bold; color: #333;">Contact number:</label>
                  <input type="text" name="contact_number" maxlength="15" id="id_contact_number" style="width: 94%; padding: 8px; border: 1px solid #ddd; border-radius: 5px; font-size: 14px;">
              </p>
          </div>

          <div class="column" style="flex: 1; display: flex; flex-direction: column; margin-right: 0;">
            <strong>{{ errors.password }}</strong>
              <p style="margin-bottom: 10px;">
                
                  <label for="id_password1" style="display: block; margin-bottom: 5px; font-weight: bold; color: #333;">Password:</label>
                  <input type="password" name="password1" autocomplete="new-password" aria-describedby="id_password1_helptext" id="id_password1" style="width: 94%; padding: 8px; border: 1px solid #ddd; border-radius: 5px; font-size: 14px;">
                  <span class="helptext" id="id_password1_helptext" style="font-size: 12px; color: #888; margin-top: 5px;">
                      <ul style="padding-left: 20px; margin: 5px 0;">
                          <li>Your password can’t be too similar to your other personal information.</li>
                          <li>Your password must contain at least 8 characters.</li>
                          <li>Your password can’t be a commonly used password.</li>
                          <li>Your password can’t be entirely numeric.</li>
                      </ul>
                  </span>
              </p>
              <p style="margin-bottom: 10px;">
                  <label for="id_password2" style="display: block; margin-bottom: 5px; font-weight: bold; color: #333;">Password confirmation:</label>
                  <input type="password" name="password2" autocomplete="new-password" aria-describedby="id_password2_helptext" id="id_password2" style="width: 94%; padding: 8px; border: 1px solid #ddd; border-radius: 5px; font-size: 14px;">
                  <span class="helptext" id="id_password2_helptext" style="font-size: 12px; color: #888; margin-top: 5px;">Enter the same password as before, for verification.</span>
              </p>
              <p style="margin-bottom: 10px;">
                  <label for="id_role" style="display: block; margin-bottom: 5px; font-weight: bold; color: #333;">Role:</label>
                  <select name="role" id="id_role" style="width: 94%; padding: 8px; border: 1px solid #ddd; border-radius: 5px; font-size: 14px;">
                      <option value="buyer" selected>Buyer</option>
                      <option value="agent">Agent</option>
                  </select>
              </p>
              <strong>{{ errors.general }}</strong>
          </div>
      </div>

      <button type="submit" style="width: 100%; padding: 10px; background-color: #E63933; color: #FFFFFF; border: none; border-radius: 5px; font-size: 16px; cursor: pointer; transition: background-color 0.3s ease;">Signup</button>
  </form>
</body>
</html> -->
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Signup form</title>
    <link rel="stylesheet" href="{% static 'property/styles/signup.css' %}">
</head>
<body>
    <form action="{% url 'signup' %}" method="POST">

        {% csrf_token %}
        <h1>Signup</h1>
        {{form}}
        <button type="submit">Signup</button>
    </form>
</body>
</html>